# Generated by Django 5.0.4 on 2024-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('push_notifications', '0010_alter_gcmdevice_options_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='gcmdevice',
			name='device_id',
			field=models.CharField(
				verbose_name="Device ID", blank=True, null=True, db_index=True,
				help_text="ANDROID_ID / TelephonyManager.getDeviceId() (always as hex)"
			),
		),
	]
